### PR TITLE
Use local code files instead of re-downloading it

### PR DESCRIPTION
**Pull request by basisbit**
Simplify development environment setup

### CODE REVIEW

**Comment by getroot** [comment]
Since it is also used by an external automatic build system, it should be possible to build with only one Docker file.

**Comment by basisbit** [comment]
What build system are you using, any details available, so that we can find a solution that works well for both?
One of the reasons for this here pull request was to be able to use Github Actions to easily build and "test" any commit to main branch or any open pull request, to simplify development.

**Comment by getroot** [comment]
We pass a single Dockerfile to Jenkins, or often a single Dockerfile to other users so they can build and use the Image.
If so, how about adding one more Dockerfile.local file that copies the local file? Or, it would be good to receive it as an option from the existing Dockerfile.

**Comment by getroot** [comment]
Our automatic build system downloads https://raw.githubusercontent.com/AirenSoft/OvenMediaEngine/{version}/Dockerfile to build airensoft/ovenmediaengine:xxx , builds it and pushes it to Dockerhub.

One of our customers uses AWS Fargate and their automated build system uses the same method.

When the Dockerfile is changed, all of these systems must be modified.

**Comment by basisbit** [comment]
Okay, I'll create a new pull request for the Dockerfile.local

**Pull request closed without merging**
