### PR TITLE
Added the sending of the closing of the stream on the webhooks.

### PR DESCRIPTION
**Pull request by trapasso**
Added a 'status' parameter to the webhooks request, this allows you to send the status of the stream: "opening" or "closing".
In this PR the sending of the streams closure has been implemented.
Opening example:
```
{                                                                                                                                                                                                                                     
  "client": {                                                                                                                                                                                                                         
    "address": "192.168.122.1",                                                                                                                                                                                                       
    "port": 44032                                                                                                                                                                                                                     
  },                                                                                                                                                                                                                                  
  "request": {                                                                                                                                                                                                                        
    "direction": "incoming",                                                                                                                                                                                                          
    "protocol": "WebRTC",                                                                                                                                                                                                             
    "status": "opening",                                                                                                                                                                                                              
    "time": "2022-02-22T11:12:03.037+01:00",                                                                                                                                                                                          
    "url": "wss://desktop-origin.local:3334/app/stream-00?direction=send&transport=tcp"                                                                                                                                               
  }                                                                                                                                                                                                                                   
}    
```
Closing example: 
```
{
  "client": {
    "address": "192.168.122.1",
    "port": 44032
  },
  "request": {
    "direction": "incoming",
    "protocol": "WebRTC",
    "status": "closing",
    "time": "2022-02-22T11:12:08.065+01:00",
    "url": "wss://desktop-origin.local:3334/app/stream-00?direction=send&transport=tcp"
  }
}
```
To the query just answer with empty json object:
```
{
}
```
Thanks in advance.

### CODE REVIEW

**Comment by getroot** [comment]
I respect you.
While I'm reviewing the code, could you please add this to the manual for other users?

**Comment by trapasso** [comment]
Manual is ok.

Thanks.

**Comment by getroot** [comment]
Thank you very much!

**Comment by hernanrz** [comment]
Hi! I'd like to know approximately when this feature will be included in a release?

**Pull request merged**
