### PR TITLE
add signed_policy_url_generator java version

### PR DESCRIPTION
**Pull request by motolies**
add signed_policy_url_generator java version

### CODE REVIEW

**Comment by getroot** [comment]
Thanks for your contribution.
- Please change the comments in the code from Korean to English.
- Is the main function for example? But could you please change it to the way it uses args[]?

**Comment by motolies** [comment]
Changed comments to English and changed to use arguments when running the program.
Please check again.

**Comment by basisbit** [comment]
imho the previous version with the easy to use "generate" function was much better. Java developers in 99% of the use cases will copy the function and call it within code, instead of using the untyped `main(String[] args)`.
I'd suggest keeping it like at the initial commit, so that it can easily be used as an example for other Java software devs.

**Comment by getroot** [comment]
@motolies What do you think of basisbit's comments? I'm honestly not a Java user so I didn't know.

**Comment by motolies** [comment]
@getroot In my personal experience, I have used a lot of frameworks such as spring rather than console applications using java.
So, it seems that many people will be able to use it more easily by providing it as a utility class rather than receiving an argument to the main function and using it.

If you want to do this, I'll change the comments to English and commit again.

@basisbit  Thanks for the good answer.

**Comment by getroot** [comment]
@motolies Please re-commit like your last comment. sorry for bothering you.

**Comment by motolies** [comment]
@getroot When I first sent a pull request to open source, I thought that each project had its own character.

Don't be sorry. I got a lot of help.

- Annotations changed to English
- Removal of unnecessary exception check due to provision of essential parameters

Please check again.
thank you

**Comment by getroot** [comment]
Thank you!

**Pull request merged**
